# SPDX-License-Identifier: MIT
#
# Makefile for GS Display Common drivers
#

# Include subdirectories
obj-$(CONFIG_GS_DRM_PANEL_UNIFIED)	+= gs_panel/
obj-$(CONFIG_GS_DRM_PANEL_UNIFIED)	+= gs_drm/
obj-$(CONFIG_GS_PANEL_SIMPLE)		+= panels/
obj-$(CONFIG_COMMON_PANEL_TEST)		+= panel_tests/ 