cmd_/home/eseidel/dev/postmarketPixel8Pro/google-zuma-hermitfeather/tools/bpf/resolve_btfids/rbtree.o := gcc -Wp,-MD,/home/eseidel/dev/postmarketPixel8Pro/google-zuma-hermitfeather/tools/bpf/resolve_btfids/.rbtree.o.d -Wp,-MT,/home/eseidel/dev/postmarketPixel8Pro/google-zuma-hermitfeather/tools/bpf/resolve_btfids/rbtree.o  -D"BUILD_STR(s)=$(pound)s"  -g -I/home/eseidel/dev/postmarketPixel8Pro/google-zuma-hermitfeather/tools/include -I/home/eseidel/dev/postmarketPixel8Pro/google-zuma-hermitfeather/tools/include/uapi -I/home/eseidel/dev/postmarketPixel8Pro/google-zuma-hermitfeather/tools/bpf/resolve_btfids/libbpf/include -I/home/eseidel/dev/postmarketPixel8Pro/google-zuma-hermitfeather/tools/bpf/resolve_btfids/libsubcmd/include -DWITH_GZFILEOP -c -o /home/eseidel/dev/postmarketPixel8Pro/google-zuma-hermitfeather/tools/bpf/resolve_btfids/rbtree.o ../../lib/rbtree.c

source_/home/eseidel/dev/postmarketPixel8Pro/google-zuma-hermitfeather/tools/bpf/resolve_btfids/rbtree.o := ../../lib/rbtree.c

deps_/home/eseidel/dev/postmarketPixel8Pro/google-zuma-hermitfeather/tools/bpf/resolve_btfids/rbtree.o := \
  /usr/include/stdc-predef.h \
  /home/eseidel/dev/postmarketPixel8Pro/google-zuma-hermitfeather/tools/include/linux/rbtree_augmented.h \
  /home/eseidel/dev/postmarketPixel8Pro/google-zuma-hermitfeather/tools/include/linux/compiler.h \
  /home/eseidel/dev/postmarketPixel8Pro/google-zuma-hermitfeather/tools/include/linux/compiler_types.h \
  /home/eseidel/dev/postmarketPixel8Pro/google-zuma-hermitfeather/tools/include/linux/compiler-gcc.h \
  /home/eseidel/dev/postmarketPixel8Pro/google-zuma-hermitfeather/tools/include/linux/types.h \
  /usr/lib/gcc/x86_64-redhat-linux/15/include/stdbool.h \
  /usr/lib/gcc/x86_64-redhat-linux/15/include/stddef.h \
  /usr/lib/gcc/x86_64-redhat-linux/15/include/stdint.h \
  /usr/include/stdint.h \
  /usr/include/bits/libc-header-start.h \
  /usr/include/features.h \
  /usr/include/features-time64.h \
  /usr/include/bits/wordsize.h \
  /usr/include/bits/timesize.h \
  /usr/include/sys/cdefs.h \
  /usr/include/bits/long-double.h \
  /usr/include/gnu/stubs.h \
  /usr/include/gnu/stubs-64.h \
  /usr/include/bits/types.h \
  /usr/include/bits/typesizes.h \
  /usr/include/bits/time64.h \
  /usr/include/bits/wchar.h \
  /usr/include/bits/stdint-intn.h \
  /usr/include/bits/stdint-uintn.h \
  /usr/include/bits/stdint-least.h \
  /usr/include/asm/types.h \
  /usr/include/asm-generic/types.h \
  /usr/include/asm-generic/int-ll64.h \
  /home/eseidel/dev/postmarketPixel8Pro/google-zuma-hermitfeather/tools/include/uapi/asm/bitsperlong.h \
  /home/eseidel/dev/postmarketPixel8Pro/google-zuma-hermitfeather/tools/arch/x86/include/uapi/asm/bitsperlong.h \
  /home/eseidel/dev/postmarketPixel8Pro/google-zuma-hermitfeather/tools/include/asm-generic/bitsperlong.h \
  /home/eseidel/dev/postmarketPixel8Pro/google-zuma-hermitfeather/tools/include/uapi/asm-generic/bitsperlong.h \
  /usr/include/asm/posix_types.h \
  /usr/include/asm/posix_types_64.h \
  /usr/include/asm-generic/posix_types.h \
  /home/eseidel/dev/postmarketPixel8Pro/google-zuma-hermitfeather/tools/include/linux/rbtree.h \
  /home/eseidel/dev/postmarketPixel8Pro/google-zuma-hermitfeather/tools/include/linux/kernel.h \
  /usr/lib/gcc/x86_64-redhat-linux/15/include/stdarg.h \
  /usr/include/assert.h \
  /home/eseidel/dev/postmarketPixel8Pro/google-zuma-hermitfeather/tools/include/linux/build_bug.h \
  /home/eseidel/dev/postmarketPixel8Pro/google-zuma-hermitfeather/tools/include/linux/math.h \
  /home/eseidel/dev/postmarketPixel8Pro/google-zuma-hermitfeather/tools/include/linux/panic.h \
  /usr/include/stdio.h \
  /usr/include/bits/types/__fpos_t.h \
  /usr/include/bits/types/__mbstate_t.h \
  /usr/include/bits/types/__fpos64_t.h \
  /usr/include/bits/types/__FILE.h \
  /usr/include/bits/types/FILE.h \
  /usr/include/bits/types/struct_FILE.h \
  /usr/include/bits/types/cookie_io_functions_t.h \
  /usr/include/bits/stdio_lim.h \
  /usr/include/bits/floatn.h \
  /usr/include/bits/floatn-common.h \
  /usr/include/stdlib.h \
  /usr/include/bits/waitflags.h \
  /usr/include/bits/waitstatus.h \
  /usr/include/sys/types.h \
  /usr/include/bits/types/clock_t.h \
  /usr/include/bits/types/clockid_t.h \
  /usr/include/bits/types/time_t.h \
  /usr/include/bits/types/timer_t.h \
  /usr/include/endian.h \
  /usr/include/bits/endian.h \
  /usr/include/bits/endianness.h \
  /usr/include/bits/byteswap.h \
  /usr/include/bits/uintn-identity.h \
  /usr/include/sys/select.h \
  /usr/include/bits/select.h \
  /usr/include/bits/types/sigset_t.h \
  /usr/include/bits/types/__sigset_t.h \
  /usr/include/bits/types/struct_timeval.h \
  /usr/include/bits/types/struct_timespec.h \
  /usr/include/bits/pthreadtypes.h \
  /usr/include/bits/thread-shared-types.h \
  /usr/include/bits/pthreadtypes-arch.h \
  /usr/include/bits/atomic_wide_counter.h \
  /usr/include/bits/struct_mutex.h \
  /usr/include/bits/struct_rwlock.h \
  /usr/include/alloca.h \
  /usr/include/bits/stdlib-float.h \
  /usr/include/byteswap.h \
  /home/eseidel/dev/postmarketPixel8Pro/google-zuma-hermitfeather/tools/include/uapi/linux/stddef.h \
  /home/eseidel/dev/postmarketPixel8Pro/google-zuma-hermitfeather/tools/include/linux/export.h \

/home/eseidel/dev/postmarketPixel8Pro/google-zuma-hermitfeather/tools/bpf/resolve_btfids/rbtree.o: $(deps_/home/eseidel/dev/postmarketPixel8Pro/google-zuma-hermitfeather/tools/bpf/resolve_btfids/rbtree.o)

$(deps_/home/eseidel/dev/postmarketPixel8Pro/google-zuma-hermitfeather/tools/bpf/resolve_btfids/rbtree.o):
