# SPDX-License-Identifier: GPL-2.0-only
#
# Audio Amplifiers Makefile
#

# Include all amplifier subdirectories
obj-y += tas256x/
obj-y += tas25xx/
obj-y += cs35l41/
obj-y += cs35l45/
obj-y += cs40l25/
obj-y += cs40l26/
obj-y += drv2624/
obj-y += audiometrics/
obj-y += snd_soc_wm_adsp/
